## Problem 3
## Problem Statement:
Print number of matches won and loss(as two columns). Consider as win when a team wins Toss  and Match . print for each and every team

In [14]:
import pandas as pd
import numpy as np
def wintoss(filename):
    df=pd.read_csv(filename)
    l1=[]
    d={}
    winlist=[]
    losslist=[]
    for i in df.values:
        l1.append(i[9])
    uniq=np.unique(l1)
    for j in uniq:
        win=0
        loss=0
        for i in df.values:
            if j==i[9] and j==i[10]:
                win=win+1
            elif j==i[2] or j==i[3]:
                loss=loss+1
        winlist.append(win)
        losslist.append(loss)
        
    d={'Teams':uniq,
       'Wins': winlist,
       'loses':losslist}
    dff=pd.DataFrame(d)
    return dff
#         # return df
wintoss('datafiles/Match.csv')

                          Teams  Wins  loses
0           Chennai Super Kings    42     89
1               Deccan Chargers    19     56
2              Delhi Daredevils    33    114
3                 Gujarat Lions    10     20
4               Kings XI Punjab    28    120
5          Kochi Tuskers Kerala     4     10
6         Kolkata Knight Riders    44    104
7                Mumbai Indians    48    109
8                 Pune Warriors     3     43
9              Rajasthan Royals    34     84
10       Rising Pune Supergiant     0      0
11      Rising Pune Supergiants     7     23
12  Royal Challengers Bangalore    35    118
13          Sunrisers Hyderabad    17     60
14                          nan     0      0